// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HillarysHairCare.Migrations
{
    [DbContext(typeof(HillarysHaircareDbContext))]
    [Migration("20240102201036_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HillarysHaircare.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean");

                    b.Property<int>("StylistId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("StylistId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentTime = new DateTime(2024, 1, 22, 8, 0, 0, 0, DateTimeKind.Local),
                            CustomerId = 1,
                            IsCancelled = false,
                            StylistId = 1
                        },
                        new
                        {
                            Id = 2,
                            AppointmentTime = new DateTime(2024, 1, 23, 9, 0, 0, 0, DateTimeKind.Local),
                            CustomerId = 2,
                            IsCancelled = false,
                            StylistId = 2
                        },
                        new
                        {
                            Id = 3,
                            AppointmentTime = new DateTime(2024, 1, 24, 10, 0, 0, 0, DateTimeKind.Local),
                            CustomerId = 3,
                            IsCancelled = false,
                            StylistId = 3
                        },
                        new
                        {
                            Id = 4,
                            AppointmentTime = new DateTime(2024, 1, 25, 11, 0, 0, 0, DateTimeKind.Local),
                            CustomerId = 4,
                            IsCancelled = false,
                            StylistId = 4
                        },
                        new
                        {
                            Id = 5,
                            AppointmentTime = new DateTime(2024, 1, 26, 12, 0, 0, 0, DateTimeKind.Local),
                            CustomerId = 5,
                            IsCancelled = false,
                            StylistId = 5
                        },
                        new
                        {
                            Id = 6,
                            AppointmentTime = new DateTime(2024, 1, 27, 13, 0, 0, 0, DateTimeKind.Local),
                            CustomerId = 6,
                            IsCancelled = false,
                            StylistId = 6
                        },
                        new
                        {
                            Id = 7,
                            AppointmentTime = new DateTime(2024, 1, 28, 14, 0, 0, 0, DateTimeKind.Local),
                            CustomerId = 7,
                            IsCancelled = false,
                            StylistId = 7
                        },
                        new
                        {
                            Id = 8,
                            AppointmentTime = new DateTime(2024, 1, 29, 15, 0, 0, 0, DateTimeKind.Local),
                            CustomerId = 8,
                            IsCancelled = false,
                            StylistId = 8
                        },
                        new
                        {
                            Id = 9,
                            AppointmentTime = new DateTime(2024, 1, 30, 16, 0, 0, 0, DateTimeKind.Local),
                            CustomerId = 9,
                            IsCancelled = false,
                            StylistId = 9
                        },
                        new
                        {
                            Id = 10,
                            AppointmentTime = new DateTime(2024, 1, 31, 17, 0, 0, 0, DateTimeKind.Local),
                            CustomerId = 10,
                            IsCancelled = false,
                            StylistId = 10
                        },
                        new
                        {
                            Id = 11,
                            AppointmentTime = new DateTime(2024, 2, 1, 18, 0, 0, 0, DateTimeKind.Local),
                            CustomerId = 11,
                            IsCancelled = false,
                            StylistId = 11
                        },
                        new
                        {
                            Id = 12,
                            AppointmentTime = new DateTime(2024, 2, 2, 19, 0, 0, 0, DateTimeKind.Local),
                            CustomerId = 12,
                            IsCancelled = false,
                            StylistId = 12
                        },
                        new
                        {
                            Id = 13,
                            AppointmentTime = new DateTime(2024, 2, 3, 20, 0, 0, 0, DateTimeKind.Local),
                            CustomerId = 13,
                            IsCancelled = false,
                            StylistId = 12
                        },
                        new
                        {
                            Id = 14,
                            AppointmentTime = new DateTime(2024, 2, 4, 21, 0, 0, 0, DateTimeKind.Local),
                            CustomerId = 14,
                            IsCancelled = false,
                            StylistId = 11
                        },
                        new
                        {
                            Id = 15,
                            AppointmentTime = new DateTime(2024, 2, 5, 22, 0, 0, 0, DateTimeKind.Local),
                            CustomerId = 15,
                            IsCancelled = false,
                            StylistId = 10
                        },
                        new
                        {
                            Id = 16,
                            AppointmentTime = new DateTime(2024, 2, 6, 23, 0, 0, 0, DateTimeKind.Local),
                            CustomerId = 16,
                            IsCancelled = false,
                            StylistId = 1
                        },
                        new
                        {
                            Id = 17,
                            AppointmentTime = new DateTime(2024, 2, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            CustomerId = 17,
                            IsCancelled = false,
                            StylistId = 2
                        },
                        new
                        {
                            Id = 18,
                            AppointmentTime = new DateTime(2024, 2, 9, 1, 0, 0, 0, DateTimeKind.Local),
                            CustomerId = 18,
                            IsCancelled = false,
                            StylistId = 3
                        },
                        new
                        {
                            Id = 19,
                            AppointmentTime = new DateTime(2024, 2, 10, 2, 0, 0, 0, DateTimeKind.Local),
                            CustomerId = 19,
                            IsCancelled = false,
                            StylistId = 4
                        },
                        new
                        {
                            Id = 20,
                            AppointmentTime = new DateTime(2024, 2, 11, 3, 0, 0, 0, DateTimeKind.Local),
                            CustomerId = 20,
                            IsCancelled = false,
                            StylistId = 5
                        });
                });

            modelBuilder.Entity("HillarysHaircare.Models.AppointmentDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("integer");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("ServiceId");

                    b.ToTable("AppointmentDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentId = 1,
                            ServiceId = 1
                        },
                        new
                        {
                            Id = 2,
                            AppointmentId = 1,
                            ServiceId = 2
                        },
                        new
                        {
                            Id = 3,
                            AppointmentId = 2,
                            ServiceId = 3
                        },
                        new
                        {
                            Id = 4,
                            AppointmentId = 2,
                            ServiceId = 4
                        },
                        new
                        {
                            Id = 5,
                            AppointmentId = 3,
                            ServiceId = 5
                        },
                        new
                        {
                            Id = 6,
                            AppointmentId = 3,
                            ServiceId = 6
                        },
                        new
                        {
                            Id = 7,
                            AppointmentId = 4,
                            ServiceId = 7
                        },
                        new
                        {
                            Id = 8,
                            AppointmentId = 4,
                            ServiceId = 8
                        },
                        new
                        {
                            Id = 9,
                            AppointmentId = 5,
                            ServiceId = 9
                        },
                        new
                        {
                            Id = 10,
                            AppointmentId = 5,
                            ServiceId = 10
                        },
                        new
                        {
                            Id = 11,
                            AppointmentId = 6,
                            ServiceId = 11
                        },
                        new
                        {
                            Id = 12,
                            AppointmentId = 6,
                            ServiceId = 12
                        },
                        new
                        {
                            Id = 13,
                            AppointmentId = 7,
                            ServiceId = 13
                        },
                        new
                        {
                            Id = 14,
                            AppointmentId = 7,
                            ServiceId = 14
                        },
                        new
                        {
                            Id = 15,
                            AppointmentId = 8,
                            ServiceId = 15
                        },
                        new
                        {
                            Id = 16,
                            AppointmentId = 8,
                            ServiceId = 1
                        },
                        new
                        {
                            Id = 17,
                            AppointmentId = 9,
                            ServiceId = 2
                        },
                        new
                        {
                            Id = 18,
                            AppointmentId = 9,
                            ServiceId = 3
                        },
                        new
                        {
                            Id = 19,
                            AppointmentId = 10,
                            ServiceId = 4
                        },
                        new
                        {
                            Id = 20,
                            AppointmentId = 10,
                            ServiceId = 5
                        },
                        new
                        {
                            Id = 21,
                            AppointmentId = 11,
                            ServiceId = 6
                        },
                        new
                        {
                            Id = 22,
                            AppointmentId = 11,
                            ServiceId = 7
                        },
                        new
                        {
                            Id = 23,
                            AppointmentId = 12,
                            ServiceId = 8
                        },
                        new
                        {
                            Id = 24,
                            AppointmentId = 12,
                            ServiceId = 9
                        },
                        new
                        {
                            Id = 25,
                            AppointmentId = 13,
                            ServiceId = 10
                        },
                        new
                        {
                            Id = 26,
                            AppointmentId = 13,
                            ServiceId = 11
                        },
                        new
                        {
                            Id = 27,
                            AppointmentId = 14,
                            ServiceId = 12
                        },
                        new
                        {
                            Id = 28,
                            AppointmentId = 14,
                            ServiceId = 13
                        },
                        new
                        {
                            Id = 29,
                            AppointmentId = 15,
                            ServiceId = 14
                        },
                        new
                        {
                            Id = 30,
                            AppointmentId = 15,
                            ServiceId = 15
                        },
                        new
                        {
                            Id = 31,
                            AppointmentId = 16,
                            ServiceId = 1
                        },
                        new
                        {
                            Id = 32,
                            AppointmentId = 16,
                            ServiceId = 2
                        },
                        new
                        {
                            Id = 33,
                            AppointmentId = 17,
                            ServiceId = 3
                        },
                        new
                        {
                            Id = 34,
                            AppointmentId = 17,
                            ServiceId = 4
                        },
                        new
                        {
                            Id = 35,
                            AppointmentId = 18,
                            ServiceId = 5
                        },
                        new
                        {
                            Id = 36,
                            AppointmentId = 18,
                            ServiceId = 6
                        },
                        new
                        {
                            Id = 37,
                            AppointmentId = 19,
                            ServiceId = 7
                        },
                        new
                        {
                            Id = 38,
                            AppointmentId = 19,
                            ServiceId = 8
                        },
                        new
                        {
                            Id = 39,
                            AppointmentId = 20,
                            ServiceId = 9
                        },
                        new
                        {
                            Id = 40,
                            AppointmentId = 20,
                            ServiceId = 10
                        });
                });

            modelBuilder.Entity("HillarysHaircare.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "John",
                            LastName = "Doe"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Jane",
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Alice",
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Bob",
                            LastName = "Williams"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Emma",
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Michael",
                            LastName = "Jones"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Olivia",
                            LastName = "Garcia"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "William",
                            LastName = "Martinez"
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Sophia",
                            LastName = "Miller"
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Liam",
                            LastName = "Davis"
                        },
                        new
                        {
                            Id = 11,
                            FirstName = "Ava",
                            LastName = "Rodriguez"
                        },
                        new
                        {
                            Id = 12,
                            FirstName = "Ethan",
                            LastName = "Gomez"
                        },
                        new
                        {
                            Id = 13,
                            FirstName = "Mia",
                            LastName = "Hernandez"
                        },
                        new
                        {
                            Id = 14,
                            FirstName = "James",
                            LastName = "Perez"
                        },
                        new
                        {
                            Id = 15,
                            FirstName = "Charlotte",
                            LastName = "Flores"
                        },
                        new
                        {
                            Id = 16,
                            FirstName = "Alexander",
                            LastName = "Adams"
                        },
                        new
                        {
                            Id = 17,
                            FirstName = "Grace",
                            LastName = "Cook"
                        },
                        new
                        {
                            Id = 18,
                            FirstName = "Daniel",
                            LastName = "Bailey"
                        },
                        new
                        {
                            Id = 19,
                            FirstName = "Luna",
                            LastName = "Kelly"
                        },
                        new
                        {
                            Id = 20,
                            FirstName = "Henry",
                            LastName = "Wright"
                        });
                });

            modelBuilder.Entity("HillarysHaircare.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 50.00m,
                            ServiceName = "Women's Haircut"
                        },
                        new
                        {
                            Id = 2,
                            Price = 40.00m,
                            ServiceName = "Men's Haircut"
                        },
                        new
                        {
                            Id = 3,
                            Price = 45.00m,
                            ServiceName = "Barber Service"
                        },
                        new
                        {
                            Id = 4,
                            Price = 80.00m,
                            ServiceName = "Hair Coloring"
                        },
                        new
                        {
                            Id = 5,
                            Price = 70.00m,
                            ServiceName = "Highlights"
                        },
                        new
                        {
                            Id = 6,
                            Price = 60.00m,
                            ServiceName = "Blowout Styling"
                        },
                        new
                        {
                            Id = 7,
                            Price = 120.00m,
                            ServiceName = "Hair Extensions"
                        },
                        new
                        {
                            Id = 8,
                            Price = 90.00m,
                            ServiceName = "Perms"
                        },
                        new
                        {
                            Id = 9,
                            Price = 100.00m,
                            ServiceName = "Bridal Hair Styling"
                        },
                        new
                        {
                            Id = 10,
                            Price = 55.00m,
                            ServiceName = "Deep Conditioning Treatment"
                        },
                        new
                        {
                            Id = 11,
                            Price = 25.00m,
                            ServiceName = "Beard Trim"
                        },
                        new
                        {
                            Id = 12,
                            Price = 30.00m,
                            ServiceName = "Shave"
                        },
                        new
                        {
                            Id = 13,
                            Price = 35.00m,
                            ServiceName = "Facial"
                        },
                        new
                        {
                            Id = 14,
                            Price = 20.00m,
                            ServiceName = "Scalp Massage"
                        },
                        new
                        {
                            Id = 15,
                            Price = 40.00m,
                            ServiceName = "Waxing"
                        });
                });

            modelBuilder.Entity("HillarysHaircare.Models.Stylist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Stylists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Emily",
                            IsActive = true,
                            LastName = "Anderson"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "David",
                            IsActive = true,
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Sophia",
                            IsActive = true,
                            LastName = "Clark"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "James",
                            IsActive = true,
                            LastName = "Davis"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Olivia",
                            IsActive = true,
                            LastName = "Garcia"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Michael",
                            IsActive = true,
                            LastName = "Harris"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Isabella",
                            IsActive = true,
                            LastName = "Jackson"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Daniel",
                            IsActive = true,
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Ava",
                            IsActive = true,
                            LastName = "Lee"
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Ethan",
                            IsActive = true,
                            LastName = "Martinez"
                        },
                        new
                        {
                            Id = 11,
                            FirstName = "Emma",
                            IsActive = true,
                            LastName = "Moore"
                        },
                        new
                        {
                            Id = 12,
                            FirstName = "William",
                            IsActive = true,
                            LastName = "Perez"
                        },
                        new
                        {
                            Id = 13,
                            FirstName = "Charlotte",
                            IsActive = false,
                            LastName = "Rivera"
                        },
                        new
                        {
                            Id = 14,
                            FirstName = "Liam",
                            IsActive = false,
                            LastName = "Roberts"
                        },
                        new
                        {
                            Id = 15,
                            FirstName = "Grace",
                            IsActive = false,
                            LastName = "Smith"
                        });
                });

            modelBuilder.Entity("HillarysHaircare.Models.Appointment", b =>
                {
                    b.HasOne("HillarysHaircare.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HillarysHaircare.Models.Stylist", "Stylist")
                        .WithMany()
                        .HasForeignKey("StylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Stylist");
                });

            modelBuilder.Entity("HillarysHaircare.Models.AppointmentDetail", b =>
                {
                    b.HasOne("HillarysHaircare.Models.Appointment", null)
                        .WithMany("AppointmentDetails")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HillarysHaircare.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("HillarysHaircare.Models.Appointment", b =>
                {
                    b.Navigation("AppointmentDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
